### PR TITLE
Update package.json

### LINKED ISSUE #13: Types section is missing in package.json
Declaration has to be listed in `package.json`'s `types` section: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

Like so:

```json
{
  "main": "use-react-router.js",
  "types": "use-react-router.d.ts"
}
```

### PR DESCRIPTION
**Pull request by kirill-konshin**
Fixes #13

### CODE REVIEW

**Comment by quisido** [comment]
Sounds good. If you can fix the TypeScript error for Travis, I'll merge. Feel free to bump the patch version if you want, and it will auto-deploy to NPM with this change.

**Comment by kirill-konshin** [comment]
Done

**Comment by quisido** [comment]
You are excellent. 👌

**Comment by kirill-konshin** [comment]
You are welcome :)

**Comment by kirill-konshin** [comment]
Works as expected btw

**Pull request merged**
